# Generated by Django 3.2 on 2022-09-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220918_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
