# Generated by Django 3.2 on 2022-10-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20221008_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preorder_item',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
