# Generated by Django 3.2 on 2022-09-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tour_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='name',
        ),
        migrations.AddField(
            model_name='tour',
            name='venue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
