# Generated by Django 3.2 on 2022-09-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='genre',
        ),
        migrations.AddField(
            model_name='member',
            name='genre',
            field=models.ManyToManyField(to='about.Genre'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='instrument',
        ),
        migrations.AddField(
            model_name='member',
            name='instrument',
            field=models.ManyToManyField(to='about.Instrument'),
        ),
    ]
