# Generated by Django 3.2 on 2022-10-12 22:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_member_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
