# Generated by Django 3.2 on 2022-10-12 23:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_member_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
